lastupdatecheck: 0
recentrepos:
- /home/joris/.config
- /home/joris/projects/2023/glassi-turborepo
- /usr/local/src/nerd-ls
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
